from __future__ import annotations

from enum import StrEnum


class AbilityTag(StrEnum):
    BLOCKER = "BLOCKER"
    S_TRIGGER = "S_TRIGGER"
    SHIELD_TRIGGER = "SHIELD_TRIGGER"
    SPEED_ATTACKER = "SPEED_ATTACKER"
    GACHINKO_JUDGE = "GACHINKO_JUDGE"
    SEARCH_SAME_NAME = "SEARCH_SAME_NAME"
    PUT_FROM_DECK_TO_BATTLE_ZONE = "PUT_FROM_DECK_TO_BATTLE_ZONE"
    DOUBLE_BREAKER = "DOUBLE_BREAKER"
    TRIPLE_BREAKER = "TRIPLE_BREAKER"
    G_STRIKE = "G_STRIKE"
    DRAW = "DRAW"
    DESTROY = "DESTROY"
    MANA_BOOST = "MANA_BOOST"
    GAIN_SHIELD = "GAIN_SHIELD"
    EVOLUTION = "EVOLUTION"
    NEO_EVOLUTION = "NEO_EVOLUTION"
    REVOLUTION_CHANGE = "REVOLUTION_CHANGE"
    INVASION = "INVASION"
    NINJA_STRIKE = "NINJA_STRIKE"
    TWINPACT = "TWINPACT"
    TAMA_SEED = "TAMA_SEED"
    PSYCHIC = "PSYCHIC"
    GR = "GR"
    SEAL = "SEAL"
    FORBIDDEN = "FORBIDDEN"
    MEKUREIDO = "MEKUREIDO"
    HYPER_MODE = "HYPER_MODE"
    COST_REDUCTION = "COST_REDUCTION"
    EXTRA_TURN = "EXTRA_TURN"
    LOCK = "LOCK"
    SEARCH = "SEARCH"
    META_EFFECT = "META_EFFECT"
    ALTERNATE_WIN_CONDITION = "ALTERNATE_WIN_CONDITION"
    SAME_NAME_MORE_THAN_4_ALLOWED = "SAME_NAME_MORE_THAN_4_ALLOWED"


KNOWN_ABILITY_TAGS = {tag.value for tag in AbilityTag}
